### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by boardy** [virtkick/source-map-resolver#1]
Hi, I am looking at using this library but can't get it work. Just wondering if you have a working example, I provide the encoded stack that I copy and paste from Chrome and when I call the method and console.log to see the new decoded version of the stack I just get the original encoded stack printed out. 

Thanks
Chris

**Comment by Nowaker** [comment]
We no longer maintain this, so unfortunately, you're on your own. :)

**Comment by boardy** [comment]
Ah Ok no probs. I think I figured what I was doing anyway I was being a numpty :)
